# 虚拟机的IP，可以通过此 IP 访问虚拟机内部启动的web应用
ip: 192.168.10.24

# 应用项目名和项目代码路径列表，这些路径将被挂载在虚拟机中的 /apps/{应用名} 目录下。
apps:
  # 请根据你的实际情况填写, 请在每行开头空两格(YAML的格式），例如
  lain: .

# 虚拟机占用的 CPU 核数
cpus: 2

# 虚拟机占用的内存数(MB)
memory: 1024
